name: Publish package to the Maven Central Repository and GitHub Packages
on:
  release:
    types: [ created ]
jobs:
  publish:
    environment: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install gpg secret key
        run: |
          echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | gpg --batch --import
          mkdir -p ~/.gradle
          touch ~/.gradle/gradle.properties
          echo 'signing.gnupg.keyName=B695879FDF4309B9DBCF07068A619BE4BF8E70B2' >> ~/.gradle/gradle.properties
          echo 'signing.gnupg.passphrase='${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} >> ~/.gradle/gradle.properties
      - name: Publish to the Maven Central Repository
        run: ./gradlew build test publish
        env:
          maven_central_username: ${{ secrets.OSSRH_USERNAME }}
          maven_central_password: ${{ secrets.OSSRH_TOKEN }}
