# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and test pull request

on:
  pull_request:
    branches: [ develop ]

jobs:
  test-pull-request-to-default-branch:

    name: Test pull request to default branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Test with gradle
        id: test
        run: ./gradlew test
      - uses: actions/upload-artifact@v2
        name: Upload test results
        if: ${{ always() && steps.test.outcome == 'failure' }}
        with:
          name: test-results
          path: build/reports/tests/test
